# Generated by Django 6.0 on 2026-01-17 00:29

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ej: Velocidad de impresión", max_length=100
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        help_text="Ej: 30 ppm (Color y B/N)", max_length=255
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especificaciones",
                        to="products.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especificación",
                "verbose_name_plural": "Especificaciones",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ProductoImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to=apps.products.models.product_image_upload_path
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0, help_text="Orden en que se mostrará en la galería"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="products.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de producto",
                "verbose_name_plural": "Imágenes de productos",
                "ordering": ["orden"],
            },
        ),
    ]
