# Generated by Django 6.0 on 2026-01-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_especificacion_productoimagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagen",
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
