# Generated by Django 6.0 on 2026-01-24 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_producto_imagen_alter_producto_descripcion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="especificacion",
            name="titulo",
        ),
        migrations.RemoveField(
            model_name="especificacion",
            name="valor",
        ),
        migrations.AddField(
            model_name="especificacion",
            name="contenido",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
