# Generated by Django 6.0 on 2026-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_subcategory_product_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta Descripción (SEO)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Meta Keywords (SEO)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Meta Título (SEO)"
            ),
        ),
    ]
