# Generated by Django 6.0 on 2026-02-01 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_meta_description_product_meta_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="Visitas"),
                ),
                (
                    "sales",
                    models.PositiveIntegerField(default=0, verbose_name="Ventas"),
                ),
                (
                    "last_visit",
                    models.DateTimeField(auto_now=True, verbose_name="Última Visita"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="products.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de Producto",
                "verbose_name_plural": "Estadísticas de Productos",
            },
        ),
    ]
