# Generated by Django 6.0 on 2026-02-01 18:08

import apps.products.models.brands
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_productstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.products.models.brands.brand_image_upload_path,
                verbose_name="Imagen",
            ),
        ),
    ]
