# Generated by Django 6.0 on 2026-02-01 19:21

import apps.products.models.categories
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_brand_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.products.models.categories.category_image_upload_path,
                verbose_name="Imagen",
            ),
        ),
    ]
