# Generated by Django 6.0 on 2026-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(
                default="No especificado",
                max_length=20,
                verbose_name="Teléfono de Contacto",
            ),
            preserve_default=False,
        ),
    ]
