# Generated by Django 6.0 on 2026-02-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="My E-commerce",
                        max_length=200,
                        verbose_name="Nombre del Sitio",
                    ),
                ),
                (
                    "site_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="Logo del Sitio",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Favicon"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de Contacto"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción corta para buscadores",
                        verbose_name="Descripción SEO (Meta)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sitio",
                "verbose_name_plural": "Configuración del Sitio",
            },
        ),
    ]
