# Generated by Django 6.0 on 2026-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="Imagen"),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Texto Botón"
                    ),
                ),
                (
                    "cta_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Enlace Botón",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["order", "-id"],
            },
        ),
    ]
