# Generated by Django 6.0 on 2026-02-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Código de Seguimiento",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre Completo / Razón Social"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Teléfono")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CE", "Carnet de Extranjería"),
                            ("RUC", "RUC"),
                            ("PASSPORT", "Pasaporte"),
                        ],
                        default="DNI",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=20, verbose_name="Número de Documento"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Dirección")),
                ("district", models.CharField(max_length=100, verbose_name="Distrito")),
                (
                    "type",
                    models.CharField(
                        choices=[("queja", "Queja"), ("reclamo", "Reclamo")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Detalle del Reclamo/Queja"),
                ),
                (
                    "amount_claimed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto Reclamado",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="claims/",
                        verbose_name="Adjunto (Evidencia)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("attended", "Atendido"),
                            ("rejected", "Rechazado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Respuesta de la empresa"
                    ),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Respuesta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Libro de Reclamaciones",
                "verbose_name_plural": "Libro de Reclamaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
